-- "Grooming Package with Trim" comes in two variants that cost Rs. 1,000 apart:
-- without knots (Rs. 6,000) and with knots (Rs. 7,000). The customer can now
-- choose, so the second variant needs to be a real bookable package — otherwise
-- picking "with knots" would be quoted at the without-knots price.
--
-- Seeds don't run on deploy (the build is migrate deploy + generate + build), so
-- the row is inserted here. `id` is spelled out because @default(cuid()) is
-- generated by Prisma in the app, not by the database.
INSERT INTO "Package" (id, key, name, "durationMin", price, standalone, active)
VALUES ('pkg_wash_trim_knots', 'wash-trim-knots', 'Grooming Package with Trim (with knots)', 120, 7000, false, true)
ON CONFLICT (key) DO NOTHING;

-- Name the existing row for the variant it actually is. Appointments reference
-- the package by id, so historical bookings keep pointing at the same row.
UPDATE "Package"
SET name = 'Grooming Package with Trim (without knots)'
WHERE key = 'wash-trim';
