-- Three à-la-carte services the salon now sells on their own: a full cat trim,
-- a cat bath, and the dog hygiene trim (sanitary areas, paw pads, eye area).
-- All three are Rs. 1,500 and live in lib/catalog.ts / lib/data.ts.
--
-- Seeds don't run on deploy (the build is migrate deploy + generate + build), so
-- the rows are inserted here. `id` is spelled out because @default(cuid()) is
-- generated by Prisma in the app, not by the database.
--
-- Each carries its OWN category rather than the shared "trim"/"bath" ones: the
-- category is what a package's `covers` list hides, and these are not hidden by
-- the same packages — Cat Bath & Care already includes the cat bath but not the
-- cat trim, and the hygiene trim is already inside the two packages that trim
-- those areas.
--
-- ON CONFLICT DO NOTHING so a re-run — or a row the salon already added by hand
-- in Settings — keeps whatever price and active flag it has now.
INSERT INTO "AddOn" (id, key, name, price, category, "group", active)
VALUES
  ('addon_cat_trim', 'cat-trim', 'Cat Full Trim', 1500, 'cat-trim', 'addon', true),
  ('addon_cat_bath', 'cat-bath', 'Cat Bath Only', 1500, 'cat-bath', 'addon', true),
  ('addon_hygiene_trim', 'hygiene-trim', 'Dog Hygiene Trim (sanitary, paw pads, eye area)', 1500, 'hygiene', 'addon', true)
ON CONFLICT (key) DO NOTHING;
